DATA CLEANING

In [4]:
import numpy as np
import pandas as pd

In [5]:
vall = np.array([1,np.NaN,7,1,8])
vall

array([ 1., nan,  7.,  1.,  8.])

In [6]:
6 +np.NaN

nan

In [7]:
7*np.nan

nan

In [8]:
np.nansum(vall)

17.0

NAN AND NONE IN PANDAS

In [9]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

Create dataframe with missing values

In [10]:
raw_data = {'First_name':['Ricky',np.nan,'John','Rim','Ravi','Tina'],
            'Last_name':['singh',np.nan,'kang','mital','rath','dev'],
            'age':[22,np.nan,23,24,25,26],
            'Sex':['M',np.nan,'M','M','M','F'],
             'unit_1':[1,np.nan,np.nan,3,4,4],
             'unit_2':[3,np.nan,np.nan,4,3,3]}
df = pd.DataFrame(raw_data,columns = ['First_name','Last_name','age','Sex','unit_1','unit_2'])
df

First_name Last_name   age  Sex  unit_1  unit_2
0      Ricky     singh  22.0    M     1.0     3.0
1        NaN       NaN   NaN  NaN     NaN     NaN
2       John      kang  23.0    M     NaN     NaN
3        Rim     mital  24.0    M     3.0     4.0
4       Ravi      rath  25.0    M     4.0     3.0
5       Tina       dev  26.0    F     4.0     3.0

Drop missing observations

In [11]:
df.dropna()


First_name Last_name   age Sex  unit_1  unit_2
0      Ricky     singh  22.0   M     1.0     3.0
3        Rim     mital  24.0   M     3.0     4.0
4       Ravi      rath  25.0   M     4.0     3.0
5       Tina       dev  26.0   F     4.0     3.0


Drop rows where all cells in the row is NA

In [12]:
df

First_name Last_name   age  Sex  unit_1  unit_2
0      Ricky     singh  22.0    M     1.0     3.0
1        NaN       NaN   NaN  NaN     NaN     NaN
2       John      kang  23.0    M     NaN     NaN
3        Rim     mital  24.0    M     3.0     4.0
4       Ravi      rath  25.0    M     4.0     3.0
5       Tina       dev  26.0    F     4.0     3.0

In [13]:
#Row that has all NaN will be removed
df.dropna(how='all')

First_name Last_name   age Sex  unit_1  unit_2
0      Ricky     singh  22.0   M     1.0     3.0
2       John      kang  23.0   M     NaN     NaN
3        Rim     mital  24.0   M     3.0     4.0
4       Ravi      rath  25.0   M     4.0     3.0
5       Tina       dev  26.0   F     4.0     3.0


create a new column full of missing values

In [14]:
df['Final_score'] = np.nan
df

First_name Last_name   age  Sex  unit_1  unit_2  Final_score
0      Ricky     singh  22.0    M     1.0     3.0          NaN
1        NaN       NaN   NaN  NaN     NaN     NaN          NaN
2       John      kang  23.0    M     NaN     NaN          NaN
3        Rim     mital  24.0    M     3.0     4.0          NaN
4       Ravi      rath  25.0    M     4.0     3.0          NaN
5       Tina       dev  26.0    F     4.0     3.0          NaN

In [15]:
# drop column if they only contain missing values
df.dropna(axis = 1,how = 'all')


First_name Last_name   age  Sex  unit_1  unit_2
0      Ricky     singh  22.0    M     1.0     3.0
1        NaN       NaN   NaN  NaN     NaN     NaN
2       John      kang  23.0    M     NaN     NaN
3        Rim     mital  24.0    M     3.0     4.0
4       Ravi      rath  25.0    M     4.0     3.0
5       Tina       dev  26.0    F     4.0     3.0

In [16]:
df.fillna(0)

First_name Last_name   age Sex  unit_1  unit_2  Final_score
0      Ricky     singh  22.0   M     1.0     3.0          0.0
1          0         0   0.0   0     0.0     0.0          0.0
2       John      kang  23.0   M     0.0     0.0          0.0
3        Rim     mital  24.0   M     3.0     4.0          0.0
4       Ravi      rath  25.0   M     4.0     3.0          0.0
5       Tina       dev  26.0   F     4.0     3.0          0.0

In [17]:
df

First_name Last_name   age  Sex  unit_1  unit_2  Final_score
0      Ricky     singh  22.0    M     1.0     3.0          NaN
1        NaN       NaN   NaN  NaN     NaN     NaN          NaN
2       John      kang  23.0    M     NaN     NaN          NaN
3        Rim     mital  24.0    M     3.0     4.0          NaN
4       Ravi      rath  25.0    M     4.0     3.0          NaN
5       Tina       dev  26.0    F     4.0     3.0          NaN


FILL IN MISSING IN UNIT_1 WITH THE MEAN VALUE OF UNIT_1

In [18]:
df['unit_1'].fillna(df['unit_1'].mean(),inplace = True)
df

First_name Last_name   age  Sex  unit_1  unit_2  Final_score
0      Ricky     singh  22.0    M     1.0     3.0          NaN
1        NaN       NaN   NaN  NaN     3.0     NaN          NaN
2       John      kang  23.0    M     3.0     NaN          NaN
3        Rim     mital  24.0    M     3.0     4.0          NaN
4       Ravi      rath  25.0    M     4.0     3.0          NaN
5       Tina       dev  26.0    F     4.0     3.0          NaN


FILL IN MISSING IN POST TEST SCORE WITH EACH SEX MEAN VALUE OF POST TEST SCORE

In [19]:
df['unit_2'].fillna(df.groupby('Sex')['unit_2'].transform('mean'),inplace = True)
df

First_name Last_name   age  Sex  unit_1    unit_2  Final_score
0      Ricky     singh  22.0    M     1.0  3.000000          NaN
1        NaN       NaN   NaN  NaN     3.0       NaN          NaN
2       John      kang  23.0    M     3.0  3.333333          NaN
3        Rim     mital  24.0    M     3.0  4.000000          NaN
4       Ravi      rath  25.0    M     4.0  3.000000          NaN
5       Tina       dev  26.0    F     4.0  3.000000          NaN


SELECT SOME RAWS BUT IGNORE THE MISSING DATA POINT

In [20]:
df[df['age'].notnull() & df['Sex'].notnull()]

First_name Last_name   age Sex  unit_1    unit_2  Final_score
0      Ricky     singh  22.0   M     1.0  3.000000          NaN
2       John      kang  23.0   M     3.0  3.333333          NaN
3        Rim     mital  24.0   M     3.0  4.000000          NaN
4       Ravi      rath  25.0   M     4.0  3.000000          NaN
5       Tina       dev  26.0   F     4.0  3.000000          NaN

In [21]:
df

First_name Last_name   age  Sex  unit_1    unit_2  Final_score
0      Ricky     singh  22.0    M     1.0  3.000000          NaN
1        NaN       NaN   NaN  NaN     3.0       NaN          NaN
2       John      kang  23.0    M     3.0  3.333333          NaN
3        Rim     mital  24.0    M     3.0  4.000000          NaN
4       Ravi      rath  25.0    M     4.0  3.000000          NaN
5       Tina       dev  26.0    F     4.0  3.000000          NaN

In [22]:
#Back fill
df.fillna(method = 'bfill')

First_name Last_name   age Sex  unit_1    unit_2  Final_score
0      Ricky     singh  22.0   M     1.0  3.000000          NaN
1       John      kang  23.0   M     3.0  3.333333          NaN
2       John      kang  23.0   M     3.0  3.333333          NaN
3        Rim     mital  24.0   M     3.0  4.000000          NaN
4       Ravi      rath  25.0   M     4.0  3.000000          NaN
5       Tina       dev  26.0   F     4.0  3.000000          NaN

In [23]:
df

First_name Last_name   age  Sex  unit_1    unit_2  Final_score
0      Ricky     singh  22.0    M     1.0  3.000000          NaN
1        NaN       NaN   NaN  NaN     3.0       NaN          NaN
2       John      kang  23.0    M     3.0  3.333333          NaN
3        Rim     mital  24.0    M     3.0  4.000000          NaN
4       Ravi      rath  25.0    M     4.0  3.000000          NaN
5       Tina       dev  26.0    F     4.0  3.000000          NaN

In [24]:
df.fillna(method = 'ffill',inplace = True)

In [25]:
df

First_name Last_name   age Sex  unit_1    unit_2  Final_score
0      Ricky     singh  22.0   M     1.0  3.000000          NaN
1      Ricky     singh  22.0   M     3.0  3.000000          NaN
2       John      kang  23.0   M     3.0  3.333333          NaN
3        Rim     mital  24.0   M     3.0  4.000000          NaN
4       Ravi      rath  25.0   M     4.0  3.000000          NaN
5       Tina       dev  26.0   F     4.0  3.000000          NaN

In [26]:
df['Final_score'].fillna(df['unit_1'] + df['unit_2'],inplace = True)

In [27]:
df

First_name Last_name   age Sex  unit_1    unit_2  Final_score
0      Ricky     singh  22.0   M     1.0  3.000000     4.000000
1      Ricky     singh  22.0   M     3.0  3.000000     6.000000
2       John      kang  23.0   M     3.0  3.333333     6.333333
3        Rim     mital  24.0   M     3.0  4.000000     7.000000
4       Ravi      rath  25.0   M     4.0  3.000000     7.000000
5       Tina       dev  26.0   F     4.0  3.000000     7.000000

In [28]:
df['Location'] = 'Bengaluru'
df

First_name Last_name   age Sex  unit_1    unit_2  Final_score   Location
0      Ricky     singh  22.0   M     1.0  3.000000     4.000000  Bengaluru
1      Ricky     singh  22.0   M     3.0  3.000000     6.000000  Bengaluru
2       John      kang  23.0   M     3.0  3.333333     6.333333  Bengaluru
3        Rim     mital  24.0   M     3.0  4.000000     7.000000  Bengaluru
4       Ravi      rath  25.0   M     4.0  3.000000     7.000000  Bengaluru
5       Tina       dev  26.0   F     4.0  3.000000     7.000000  Bengaluru


TITANIC DATA SET

In [29]:
titanic_train = pd.read_csv('https://raw.githubusercontent.com/training-ml/Files/main/titanic_train.csv')
titanic_train.head()

Unnamed: 0  PassengerId  Survived  Pclass  \
0           0            1         0       3   
1           1            2         1       1   
2           2            3         1       3   
3           3            4         1       1   
4           4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S


HOW TO CHECK UNIQUE VALUES OF ANY COLUMN

In [30]:
titanic_train['Survived'].unique() #similarly you can check any column unique value

array([0, 1], dtype=int64)

 HOW TO RENAME CATEGORIES USING PANDAS METHOD

In [31]:
new_survived = pd.Categorical(titanic_train['Survived'])
new_survived = new_survived.rename_categories(['Dead','Survived'])
new_survived.describe()

counts     freqs
categories                  
Dead           549  0.616162
Survived       342  0.383838

In [32]:
titanic_train['Pclass'].unique()

array([3, 1, 2], dtype=int64)

In [33]:
new_Pclass = pd.Categorical(titanic_train['Pclass'],ordered = True)
new_Pclass = new_Pclass.rename_categories(['class1','class2','class3'])
new_Pclass.describe()

counts     freqs
categories                  
class1         216  0.242424
class2         184  0.206510
class3         491  0.551066

In [34]:
#Reassign new name to Pclass
titanic_train['Pclass'] = new_Pclass

In [35]:
titanic_train.head()

Unnamed: 0  PassengerId  Survived  Pclass  \
0           0            1         0  class3   
1           1            2         1  class1   
2           2            3         1  class3   
3           3            4         1  class1   
4           4            5         0  class3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [41]:
titanic_train['Cabin'].unique() #check unique cabin

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [45]:
char_cabin = titanic_train['Cabin'].astype(str) # convert data to str
# List comprehension(creating list using anoyher type of string,list etc)
new_cabin = np.array([cabin[0] for cabin in char_cabin])# Take first letter
new_cabin = pd.Categorical(new_cabin)
new_cabin.describe()

counts     freqs
categories                  
A               15  0.016835
B               47  0.052750
C               59  0.066218
D               33  0.037037
E               32  0.035915
F               13  0.014590
G                4  0.004489
T                1  0.001122
n              687  0.771044

In [46]:
titanic_train['Cabin'] = new_cabin

In [49]:
titanic_train.head(10)

Unnamed: 0  PassengerId  Survived  Pclass  \
0           0            1         0  class3   
1           1            2         1  class1   
2           2            3         1  class3   
3           3            4         1  class1   
4           4            5         0  class3   
5           5            6         0  class3   
6           6            7         0  class1   
7           7            8         0  class3   
8           8            9         1  class3   
9           9           10         1  class2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500     n        S  
1      0          PC 17599  71.2833     C        C  
2      0  STON/O2. 3101282   7.9250     n        S  
3      0            113803  53.1000     C        S  
4      0            373450   8.0500     n        S  
5      0            330877   8.4583     n        Q  
6      0             17463  51.8625     E        S  
7      1            349909  21.0750     n        S  
8      2            347742  11.1333     n        S  
9      0            237736  30.0708     n        C




FIND ALL THE PASSENGERS WHOSE AGE IS MISSING

In [51]:
## np.where gives the index of those missing data
missing = np.where(titanic_train['Age'].isnull() == True) # Find all nulls in column age
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154, 158, 159, 166, 168, 176, 180, 181, 185, 186,
        196, 198, 201, 214, 223, 229, 235, 240, 241, 250, 256, 260, 264,
        270, 274, 277, 284, 295, 298, 300, 301, 303, 304, 306, 324, 330,
        334, 335, 347, 351, 354, 358, 359, 364, 367, 368, 375, 384, 388,
        409, 410, 411, 413, 415, 420, 425, 428, 431, 444, 451, 454, 457,
        459, 464, 466, 468, 470, 475, 481, 485, 490, 495, 497, 502, 507,
        511, 517, 522, 524, 527, 531, 533, 538, 547, 552, 557, 560, 563,
        564, 568, 573, 578, 584, 589, 593, 596, 598, 601, 602, 611, 612,
        613, 629, 633, 639, 643, 648, 650, 653, 656, 667, 669, 674, 680,
        692, 697, 709, 711, 718, 727, 732, 738, 739, 740, 760, 766, 768,
        773, 776, 778, 783, 790, 792, 793, 815, 825, 826, 828, 832, 837,
        839, 846, 849, 859, 863, 868, 878, 888], dt

In [52]:
# Using the index locate passangers
titanic_train.loc[missing]

Unnamed: 0  PassengerId  Survived  Pclass  \
5             5            6         0  class3   
17           17           18         1  class2   
19           19           20         1  class3   
26           26           27         0  class3   
28           28           29         1  class3   
..          ...          ...       ...     ...   
859         859          860         0  class3   
863         863          864         0  class3   
868         868          869         0  class3   
878         878          879         0  class3   
888         888          889         0  class3   

                                         Name     Sex  Age  SibSp  Parch  \
5                            Moran, Mr. James    male  NaN      0      0   
17               Williams, Mr. Charles Eugene    male  NaN      0      0   
19                    Masselmani, Mrs. Fatima  female  NaN      0      0   
26                    Emir, Mr. Farred Chehab    male  NaN      0      0   
28              O'Dwyer, Miss. Ellen "Nellie"  female  NaN      0      0   
..                                        ...     ...  ...    ...    ...   
859                          Razi, Mr. Raihed    male  NaN      0      0   
863         Sage, Miss. Dorothy Edith "Dolly"  female  NaN      8      2   
868               van Melkebeke, Mr. Philemon    male  NaN      0      0   
878                        Laleff, Mr. Kristo    male  NaN      0      0   
888  Johnston, Miss. Catherine Helen "Carrie"  female  NaN      1      2   

         Ticket     Fare Cabin Embarked  
5        330877   8.4583     n        Q  
17       244373  13.0000     n        S  
19         2649   7.2250     n        C  
26         2631   7.2250     n        C  
28       330959   7.8792     n        Q  
..          ...      ...   ...      ...  
859        2629   7.2292     n        C  
863    CA. 2343  69.5500     n        S  
868      345777   9.5000     n        S  
878      349217   7.8958     n        S  
888  W./C. 6607  23.4500     n        S  

[177 rows x 13 columns]



FIND THE MAXIMUM FARE




In [53]:
INDEX = np.where(titanic_train['Fare'] == max(titanic_train['Fare']))
INDEX

(array([258, 679, 737], dtype=int64),)

In [59]:
titanic_train.loc[INDEX]

Unnamed: 0  PassengerId  Survived  Pclass  \
258         258          259         1  class1   
679         679          680         1  class1   
737         737          738         1  class1   

                                   Name     Sex   Age  SibSp  Parch    Ticket  \
258                    Ward, Miss. Anna  female  35.0      0      0  PC 17755   
679  Cardeza, Mr. Thomas Drake Martinez    male  36.0      0      1  PC 17755   
737              Lesurer, Mr. Gustave J    male  35.0      0      0  PC 17755   

         Fare Cabin Embarked  
258  512.3292     n        C  
679  512.3292     B        C  
737  512.3292     B        C



FIND THE FAMILY WHO HAS HIGHEST MEMBERS

In [62]:
# Sibsp and parch are siblings and parents/guardian respectively(add both of them and create column)
titanic_train['Family'] = titanic_train['SibSp'] + titanic_train['Parch']
most_family = np.where(titanic_train['Family'] == max(titanic_train['Family']))
titanic_train.loc[most_family]

Unnamed: 0  PassengerId  Survived  Pclass  \
159         159          160         0  class3   
180         180          181         0  class3   
201         201          202         0  class3   
324         324          325         0  class3   
792         792          793         0  class3   
846         846          847         0  class3   
863         863          864         0  class3   

                                  Name     Sex  Age  SibSp  Parch    Ticket  \
159         Sage, Master. Thomas Henry    male  NaN      8      2  CA. 2343   
180       Sage, Miss. Constance Gladys  female  NaN      8      2  CA. 2343   
201                Sage, Mr. Frederick    male  NaN      8      2  CA. 2343   
324           Sage, Mr. George John Jr    male  NaN      8      2  CA. 2343   
792            Sage, Miss. Stella Anna  female  NaN      8      2  CA. 2343   
846           Sage, Mr. Douglas Bullen    male  NaN      8      2  CA. 2343   
863  Sage, Miss. Dorothy Edith "Dolly"  female  NaN      8      2  CA. 2343   

      Fare Cabin Embarked  Family  
159  69.55     n        S      10  
180  69.55     n        S      10  
201  69.55     n        S      10  
324  69.55     n        S      10  
792  69.55     n        S      10  
846  69.55     n        S      10  
863  69.55     n        S      10